# Generated by Django 5.0.3 on 2024-03-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('fats', models.FloatField()),
                ('carbs', models.FloatField()),
                ('proteins', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.ManyToManyField(to='BZYCalculator.food')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('food_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BZYCalculator.foodcart')),
            ],
        ),
        migrations.AddField(
            model_name='foodcart',
            name='cart_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BZYCalculator.user'),
        ),
    ]
