# Generated by Django 5.0.3 on 2024-03-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BZYCalculator', '0002_customuser_remove_foodcart_cart_id_foodcart_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
