# Generated by Django 5.0.3 on 2024-03-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BZYCalculator', '0003_customuser_is_active_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
