# Generated by Django 5.0.3 on 2024-03-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BZYCalculator', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
