# Generated by Django 5.0.3 on 2024-04-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BZYCalculator', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.FloatField(null=True),
        ),
    ]
